### ISSUE TITLE
import {JSONPath} from 'jsonpath-plus' for ESM

### ISSUE THREAD

**Issue by ahutchinson1** [s3u/JSONPath#100]
Just a note about the directions in the README. 

I'm using the 'esm' module for ES6 support in node.js and I had to do 
`import {JSONPath} from 'jsonpath-plus';` 
for it to work. If I just did 
`import JSONPath from 'jsonpath-plus'; `
it would give an error that the module did not export a 'default', or something like that.

**Comment by brettz9** [comment]
Thanks for the report! Fixed in `master`...
