### ISSUE TITLE
Improve error message for missing `json` property in constructor

### ISSUE THREAD

**Issue by rozele** [s3u/JSONPath#110]
Given the following:
```
new JSONPath({ path: "$" })
```
The error message is:
```
You must supply a "path" property when providing an object argument to JSONPath.evaluate().
```
It should probably be:
```
You must supply a "json" property when providing an object argument to JSONPath.evaluate().
```

**Comment by brettz9** [comment]
Added in v2.0.0. Thanks for the report.

Note that if `json` is present but `undefined`, it will still not throw, as there is the potential one is trying to query `undefined`.
