### ISSUE TITLE
ResultType "parentProperty" always results in ResultType of "value"

### ISSUE THREAD

**Issue by pyoor** [s3u/JSONPath#119]
When setting the resultType to "parentProperty", the result will throw due to the resultType.toLowercase() and then this switch statement:

https://github.com/s3u/JSONPath/blob/c630cd1ebdcf67740b3ec80dd6af8053058154c6/src/jsonpath.js#L347-L365

Furthermore, even if the case statement is set to lowercase ("parentproperty"), the result will fail due to the object property casing (i.e. "parentProperty").

**Comment by brettz9** [comment]
Fixed now in v4.0.0. Thanks for the report!
