### ISSUE TITLE
Differentiate between object and array of objects

### ISSUE THREAD

**Issue by pradp** [s3u/JSONPath#19]
```
var sample1 = {
  "book" : {
    "name" : "book 1",
    "type" : "type 1"
  }
}

var sample2 = {
  "book" : [{
      "name" : "book 1",
      "type" : "type 1"
    }, {
      "name" : "book 2",
      "type" : "type 2"
    }, {
      "name" : "book 3",
      "type" : "type 3"
    }
  ]
}
```
Can any one help me to construct a single JSON path to extract the book name for which the type = "type 1" from both the samples? The problem is the book can be an array or an object but I can have only one json path to extract the value. Any help would be appreciated.

**Comment by brettz9** [comment]
You can now use `@object()`, `@array()` or some other type options.
