### ISSUE TITLE
getting property names as data

### ISSUE THREAD

**Issue by chrisdew** [s3u/JSONPath#22]
I have some JSON which includeds objects-used-as-dictionaries.  

Is it possible to get keys from objects using JSONPath, if you do not know the names of the keys in advance of seeing the data?

e.g. I would like to get the results ["France","Spain"] from a JSONPath quesry on:

{
  "capitals":{
    "France":"Paris",
    "Spain":"Madrid"
  }
}

**Comment by brettz9** [comment]
Properties are now available for retrieval with the tilde (`~`). See the new docs.
