### ISSUE TITLE
Doesn't return object when '.' used in the object name

### ISSUE THREAD

**Issue by nbu** [s3u/JSONPath#24]
Have object:

    var obj = {
      "test1": {
        "test2": {
          "test3.test4.test5": {
            "test7": "value"
          }
        }
      }
    }

Doing request:

    jsonPath.eval(obj, "test1.test2['test3.test4.test5']")
    or
    jsonPath.eval(obj, 'test1.test2["test3.test4.test5"]')

in both cases returns: 

    []

Expectation is:

    {
      "test7": "value"
    }

**Comment by brettz9** [comment]
This support has now been added. Your test case was specifically added to the tests too. Thanks!
