### ISSUE TITLE
Decouple matcher from traversal?

### ISSUE THREAD

**Issue by dominictarr** [s3u/JSONPath#3]
would it be possible do decouple the part that finds the matching objects from the part that traverses the tree?

over here at https://github.com/Floby/node-json-streams/issues/4   
we're working on a streaming parser and need something to select the parts of the json object once they are discovered.

this basically involves a traversal, but it is asyncronous.

what input do you need to make JSONPath work?

is a root object, a path, and a current object enough?

**Comment by brettz9** [comment]
@dominictarr : I think this has become the more active project, so a PR would be most welcome! Note that our current version of JSONPath now allows for a callback to execute during traversal, but it is not asynchronous, nor is it pull parsing.

**Comment by dominictarr** [comment]
@brettz9 thanks but after reviewing a couple of libraries like this I ended up just going with rolling my own path thing that is much simpler (supporting * but not recursive patterns, or relative patterns etc, but later I got a pull request that added ** as a recursive match, but the problem with that is it makes memory use less predictable.)

anyway, that was for https://github.com/dominictarr/JSONStream which turned out to be very useful even without a very complex path matching system.

**Comment by brettz9** [comment]
Thanks for the update and info! FYI, the standard JSON Pointer syntax might meet some needs for simple traversal (if it is not too simple).

In our case allowing for more arbitrary searching, it's a pity I think that with everyone having stampeded to use JSON (though for some good reasons), we still don't have a JSON standard equivalent for XPath or even CSS-selectors, let alone a browser-built-in syntax. Hopefully, we can make it robust enough. I'd similarly like to see strong equivalents for schemas become well-established and supported (JSON Schema) and even XSLT (I'm hoping to find time to build up my still non-functional, pre-alpha project, [JTLT](https://github.com/brettz9/jtlt/) for this purpose).

**Comment by dominictarr** [comment]
just becareful that you don't frighten everyone away to whatever replaces JSON? ;)

**Comment by brettz9** [comment]
Hehe :)
