### ISSUE TITLE
The proper syntax to filter equal condition

### ISSUE THREAD

**Issue by dongliu** [s3u/JSONPath#34]
I spend a while to go through the document and code to figure this out. 

An expression like `$..book[?(@.title='"Sword of Honour"')]` will not work. 

It should be something like `$..book[?(@.title=='"Sword of Honour"')]` or `$..book[?(@.title==='"Sword of Honour"')]` like in JavaScript. Not sure if this is obvious, but I suggest to add it to the document since it is different from XPath syntax. Thanks.

**Comment by brettz9** [comment]
Added in PR #35
