### ISSUE TITLE
npm package not 0.11.0?

### ISSUE THREAD

**Issue by dai-shi** [s3u/JSONPath#40]
$ npm install JSONPath
    JSONPath@0.10.0 node_modules/JSONPath

Isn't it 0.11.0?

BTW,
https://www.npmjs.com/package/JSONPath
says 404.

**Comment by austundag** [comment]
+1.  Can you please publish 0.11.0?

**Comment by gpempro** [comment]
+1

**Comment by mshick** [comment]
This would be great. Just spent awhile debugging problems due to the change in syntax before noticing the version difference.

**Comment by mellema** [comment]
npm still installing 0.10.0, which has the deprecated "eval" stuff in it.

**Comment by alexandernst** [comment]
+1

**Comment by vjpr** [comment]
+1

**Comment by Marsiou** [comment]
+1

**Comment by nobusue** [comment]
+1

**Comment by brettz9** [comment]
s3u has kindly added me to the owner's list, and I've pushed changes as 0.11.0. Please bear in mind that among the changes there is one minor but necessary breaking change:

```
Breaking change: For unwrapped results, return undefined instead of false
upon failure to find path (to allow distinguishing of undefined--a non-allowed
JSON value--from the valid JSON, null or false) and return the exact value
upon falsy single results (in order to allow return of null)
```

There are also a few property-related fixes (e.g., to allow special characters within them) and many new features (including some operators not present in the original JSONPath spec, such as property retrieval).

@mellema : Please note that we are currently only deprecating `jsonpath.eval()`, but not removing usage of `eval()`, as we need an updated version of PR #4 (see the new issue #53 ). There is, for the time being at least, a new `preventEval` option to avoid allowance for eval'd JavaScript expressions (as these definitely can have consequences).

**Comment by brettz9** [comment]
The latest package for npm with "JSONPath" as the name is at 0.11.2. I have added a warning there that the new npm name has been changed to "jsonpath-plus" (see issue #54 ). Sorry to get this out to you now, but hadn't noticed the issue requesting this until after version 0.11.0. The repo is still hosted here, but if you are using Node, you will wish to update to use "jsonpath-plus" instead.
