### ISSUE TITLE
Angular-mock and JSONPath problems

### ISSUE THREAD

**Issue by matpimenta** [s3u/JSONPath#42]
We are having problems using JSONPath and angular-mock at the same time in Karma. After some debugging we found out that angular-mock creates a window.module variable. 
This causes JSONPath to not create the window.JSONPath function.

From the code:
```js
if (typeof module === 'undefined') {
    window.jsonPath = { // Deprecated
        eval: JSONPath.eval
    };
    window.JSONPath = JSONPath;
}
else {
    module.exports = JSONPath;
}
```

The only way around now is to make sure that JSONPath loads before the angular-mock file.

**Comment by brettz9** [comment]
I have just now added commit a1ffede8e0852cde7fe80d6c309094d2a72f076c to `master` which should fix your issue. If not, feel free to comment further, and I will reopen.
