### ISSUE TITLE
ie8 issue

### ISSUE THREAD

**Issue by shinta5150** [s3u/JSONPath#43]
TypeError: Object doesn't support this property or method
Occurs on this line:
var ret = this.evaluate((objArgs ? opts.json : obj), (objArgs ? opts.path : expr));

The json string is '$.questions[?(@.name==\'questioame\')]

**Comment by brettz9** [comment]
IE8 is not currently supported. You would at least need an `Object.keys` and `Array.prototype` methods (`reduce`,`map`, and `filter`) polyfilled and possibly others.

Unless @s3u wants to override and reopen the issue, I don't think we should be working at IE8 support.
