### ISSUE TITLE
Sandbox parameters don't work

### ISSUE THREAD

**Issue by mglazer-cengage** [s3u/JSONPath#44]
I don't see any tests for using sandbox parameters and they don't seem to work

```js
json = {"books":[{"title":"kids", "author":"adams"},{"title":"action", "author":"johns"}]}

path = '$..books[?(@.title==@.param)]'

JSONPath({json:json, path : path, sandbox : {param:'kids'}} )
```

This JSBIN demonstrates this with two test:

http://jsbin.com/cupehuyayo/edit

The first test above is with the param second is with a string

Any help would be appreciated, thank you.

**Comment by brettz9** [comment]
In your case, it should be:

```js
var ext = param ? 'param' : '"kids"';
```

I've also added a test to `master`.

Feel free to comment further, but closing as should be addressed now.
