### ISSUE TITLE
How to change value using json path?

### ISSUE THREAD

**Issue by PositiveAlex** [s3u/JSONPath#47]
I'm a noob user, trying to understand, could i create tests on my api with nodejs + json path.

My common tasks would be to fill up empty jsons with data, but using paths (i need to maintain actively growing and changing API service, that's why i cannot duplicate json object in tests, i need to load it from prepared file with json text, downloaded from dev git repository, this json file is a latest representation of a request considering the latest specification). If I won't do this, I will need to change all tests every time when api would change inside of the development process. 

In Ruby implementation of jsonpath I can get access to the object right when i'm executing json path and change a value of finded node on the fly.

How could this be possible in node? 

I found essential to use node js to test ***json*** API, but for now  it seems that ruby community is more prepared for that... or am I wrong?

**Comment by brettz9** [comment]
In the latest release, you can request `resultType: "all"` and utilize the `parent` and `parentProperty` to modify the object. The `callback` option can be used to modify during iteration. Feel free to continue to comment, but am closing as this should address the question.

**Comment by jwatts21** [comment]
modifications made in the callback function is not reflected in final output... am I missing something?

let books = {
  "store": {
    "book": 
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}

let callback = (payload, type, obj) => {
  payload.category = 'foo';
  return payload;
};

const rs = JSONPath({
  path: '$..book[?(@.price<10)]',
  json: books,
  callback
});
console.log(JSON.stringify(rs,null,' '))

Thanks

**Comment by brettz9** [comment]
It is showing `"category": "foo"` for me in both the browser (Firefox or Chrome) and Node. What version/environment are you using?

(I did edit your example to add a missing square bracket after `"book":`, so is it possible you weren't getting different results because of that?)
