### ISSUE TITLE
JsonPath Conditions Data

### ISSUE THREAD

**Issue by keshavwork** [s3u/JSONPath#52]
Dear All 
please help bellow example.

```js
 var masterdata = {
    "seedData": {
        "eligibleChargeTypes": {
            "eligibleChargeType": [
                {
                    "code": "Activation",
                    "name": "Activation",
                    "resource": {
                        "code": "Both",
                        "name": "Both"
                    }
                },
                {
                    "code": "ProductChange",
                    "name": "Product Change"
                }
            ]
        }
    }
}
```

Expected out put :"code": "Activation"

if resource.code =''both' is sucess then i need the parent one data. 

```
output= "";
output += jsonPath(masterdata, "$.seedData.eligibleChargeTypes.eligibleChargeType[*].resource[?(@.code=='Both')]..code").toJSONString() + "\n>";


 document.write(output);
```

**Comment by brettz9** [comment]
If you have questions on how to use JSONPath, please ask them on the likes of 
http://stackoverflow.com/ (with the "jsonpath" tag).

If you look at the [README](https://github.com/s3u/JSONPath#readme), you should see that `^` is the parent selector, but in this case, I don't think you need it. Note also that the syntax order has changed from `jsonPath.eval` to `JSONPath`. To help you get started, I have added a working adaptation of your code at http://jsbin.com/qesiwilani/1/edit?html,js,console,output but please ask questions on usage at StackOverflow or another question site.
