### ISSUE TITLE
republish to npm with lowercase name

### ISSUE THREAD

**Issue by deyhle** [s3u/JSONPath#54]
npm does not accept uppercase characters in package names anymore. While it still does work with JSONPath, it leads to a myriad of problems – especially now with npm 3. Due to the flat dependences this module conflicts with the [jsonpath package](https://www.npmjs.com/package/jsonpath) – which will not work on case-insensitive file systems.

So the best solution would probably be to republish JSONPath to npm under a new name with lowercase characters, and to make a note in the current version to better use the new package. 

npm will likely not fix the issue on their side, they just hope that the problem will go away sometime – also see [this npm issue](https://github.com/npm/npm/issues/9671).

**Comment by brettz9** [comment]
Thanks for the report. We have renamed in npm to `jsonpath-plus` (also reflecting the fact that we have now added some features not present in the original JSONPath spec). (I also added version 0.11.2 on npm to alert people to the move).

**Comment by richardschneider** [comment]
@brettz9 thanks for all the hard work.  Is there any documentation on the new features not in the original spec?

**Comment by brettz9** [comment]
The following from the CHANGES file are not in the original spec:

```markdown
- Feature: Allow type operators: JavaScript types (`@boolean()`, `@number()`, `@string()`), other fundamental JavaScript types (`@null()`, `@object()`, `@array()`), the JSONSchema-added type, `@integer()`, and the following non-JSON types that can nevertheless be used with JSONPath when querying non-JSON JavaScript objects (`@undefined()`, `@function()`, `@nonFinite()`). Finally, `@other()` is made available in conjunction with a new callback option, `otherTypeCallback`, can be used to allow user-defined type detection (at least until JSON Schema awareness may be provided).
- Feature: Support custom `@parent`, `@parentProperty`, `@property` (in addition to custom property `@path`) inside evaluations
- Feature: Support a custom operator (`~`) to allow grabbing of property names
- Feature: Support `$` for retrieval of root, and document this as well as `$..` behavior
```

Note that I included the last feature in this list because `$..` (as opposed to `$..*` or `$`) was not documented.

**Comment by brettz9** [comment]
The notes column of the table also documents these as divergences from the original spec.

Note that the `[?(@['...'])]` and `[(@['...'])]` syntax to allow special characters in filtering properties is another divergence (or at least previously unspecified feature) was not in the previous releases (only in `master`).
