### ISSUE TITLE
Feature: get all paths in an object

### ISSUE THREAD

**Issue by BryanDonovan** [s3u/JSONPath#6]
A very useful feature (for me anyway) would be a method that lets you get all the paths in an object.  Something like:

jsonpath.paths(obj);

.. and have it return an array of unique paths.

The use case for me is to compare two JSON objects and assert that they have the same JSONPaths, ignoring the count and order of how the paths occur in the objects.

**Comment by brettz9** [comment]
While I can see the utility of this proposal (Node has its `assert.deepEqual` though sadly the browser does not), my thinking is that it is more a specific use case (as already described in my previous comment). Feel free to comment further, however, as we can reopen if we come to another conclusion.
