### ISSUE TITLE
Error when using from Rhino: ReferenceError: "self" is not defined. (jsonpath-0.13.0.js#449)

### ISSUE THREAD

**Issue by sglebs** [s3u/JSONPath#67]
I am experimenting with a fix for https://github.com/smartrics/RestFixture/issues/157 and in the process I am trying jsonpath. Unfortunately, when I try to use it 0.13.0, I get:

```
ReferenceError: "self" is not defined. (jsonpath-0.13.0.js#449)
```

**Comment by sglebs** [comment]
The fix is to replace "self." with "this." in both lines:
```
else {
    this.jsonPath = { // Deprecated
        eval: JSONPath.eval
    };
    this.JSONPath = JSONPath;
}
```

**Comment by brettz9** [comment]
I've noticed that `this` doesn't work nicely with Jasmine, requiring `self` in such cases. Maybe we could check for `self` and if not present resort to `this`...

**Comment by brettz9** [comment]
I've committed a change to `master`. Let me know if you need this in a release.
