### ISSUE TITLE
Return result not documented; question on returning an array of properties

### ISSUE THREAD

**Issue by cfjedimaster** [s3u/JSONPath#68]
Please forgive the title. I don't think it is a great one but I had difficulty coming up with an appropriate one for the bug report.

Given the source JSON, using `$.store.book[*].author` is meant to return each author value. In my testing, this worked, but I noticed my callback was called 4 times as opposed to being called once with an array of four items. This seems odd as $.store.book will call the callback once and send everything. 

I'm working on a generic viewer for JSONPath and because of this, I don't know when the work is done - if that makes sense. 

Is this expected?

**Comment by irritanterik** [comment]
I think so. The callback option is specifically for handling each individual result. If you want to retrieve the result array in a variable use something like:
var result = jsonPath({json: result.data, path: args.path});

**Comment by cfjedimaster** [comment]
So two things:

Is there a way to know that $.store.book is an array but one result, but $.store.book[*].author is 4 results? My mind can't seem to see the difference.

Secondly - is x = jsonPath documented? I had assumed you *must* use the callback.

**Comment by brettz9** [comment]
Because the `callback` executes once for each result, and `$.store.book` is only one item (an array), it executes once whereas `$.store.book[*].author` returns four times because there are 4 separate authors. 

The source of your confusion might be that because `$.store.book` is an array of multiple items, you are thinking that it should return multiple times, but it is really just a single item (an array) whereas `author` is not an array, but the JSONPath expression finds four separate instances of that property so that is why it executes for times.

**Comment by brettz9** [comment]
As far as the documentation of the return result, while it may be a little implicit with the fact that `callback` is mentioned as being optional, I agree this should be made more clear. Would be great to get a PR for this if you could.

**Comment by cfjedimaster** [comment]
I'll write up something and do a PR.

**Comment by brettz9** [comment]
Thanks for the PR! I've made some subsequent changes. See if that works for you...

**Comment by cfjedimaster** [comment]
Your text isn't a change - it's completely different, and about 500% better. Thank you. ;)

**Comment by brettz9** [comment]
Glad to hear it! Btw, I discovered that one unit test is failing which I hope to have a fix out for shortly.

**Comment by brettz9** [comment]
Btw, @cfjedimaster , two important points related to your earlier question.

If you set `flatten` to `true`, then you won't be able to distinguish between return results which are an array and those which are a string. For example, if your JSON is:

```json
{
    "item1": ["abc"],
    "item2": "abc"
}
```

...the path `$..*`, will return:

```json
["abc", "abc", "abc"]
```

...where the first "abc" is the array flattened from `item1`, the second "abc" is the string in `item2`, and the third "abc" is the string at `item1[0]`.

The second point is that with the property `wrap` (whose docs I just updated as well to give more clarification), unfortunately, the default had been set to `true` which can produce ambiguous results if the result could be either an empty array or a failure to find anything.

**Comment by cfjedimaster** [comment]
1) But that's only an issue if you do that, right? And use x=JSONPath() versus the callback... right?

2) Ok, so is wrap's default now false?

**Comment by brettz9** [comment]
1. Yes, it's only an issue if you change the default by adding `flatten: true`. And yes, that would only pertain to the return result. (FYI, you can of use the return result AND use a callback if you wish)

2. The default is still `false` in master, but I've added an issue for version 1.0 to change its default to `true`.

**Comment by brettz9** [comment]
It's a breaking change, so even though we're still in version 0.x, I'd like to minimize breaking changes until ready.
