### ISSUE TITLE
The problem in the browser below IE9-

### ISSUE THREAD

**Issue by ccefeg** [s3u/JSONPath#73]
In the browser below IE9-, it have a problem.
the browser bleow IE9- not support the function 'Array.isArray'.

**Comment by brettz9** [comment]
You can add your own file to add support for `Array.isArray` with a polyfill such as at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Polyfill

I don't think we should be baking in polyfills, especially when the feature is already supported by all modern browsers, so I will close, though feel free to continue commenting.
