### ISSUE TITLE
is there a "In" operator in the JSONPath for arrays.

### ISSUE THREAD

**Issue by dlsagayaraj** [s3u/JSONPath#75]
var data = {
        grouped_people: {
            'friends': [
                {name: 'Steve', country: ['NZ','US']},
                {name: 'Daniel', country: ['NZ']},
                {name: 'Bob', country: ['US']}
            ],
            'enemies': [
                {name: 'Evil Steve', country: ['NZ','US']}
            ]
        }
    }

i am trying to get people who have country as "US",  which should result in getting me the records of Steve,Bob, and Evil Steve. 

I tried this below query but it gets me only the Bob.  
  
var values=    JSONPath({json: data, path: "$..[?(@.country=='US')]"});

Is there anything i could use to specify "in"/"has" operator for an array?
some thing like below. 

var values=    JSONPath({json: data, path: "$..[?('US' in @.country)]"});

**Comment by brettz9** [comment]
The content of the filters (e.g. `@.country=='US'`) is going to be evaluated JavaScript (with the `@` replaced). So use JavaScript `indexOf` to test, though making sure that the property exists before acting on it:

```
$..[?(@.country && @.country.indexOf('US') > -1)]
```

I'm closing, but feel free to comment further.
