### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by amitguptagwl** [s3u/JSONPath#79]
As I read on readme about performance issue, I compared it with 3 more implementations of jsonpath. And I found this has the better performance than all.

Check the report here
https://naturalintelligence.github.io/comparejs/?q=jsonpath-comparison

**Comment by brettz9** [comment]
Great to have this data--I'm closing though if you wouldn't mind adding your comments to #14 for discussion there to allow further discussion there (and perhaps where you could see whether your test cases cover the kinds of conditions reported there).
