### ISSUE TITLE
Results with the same reference as the document

### ISSUE THREAD

**Issue by gitfy** [s3u/JSONPath#8]
Hi,
Is it possible to have an optional feature to return the matching elements of an document, with reference to it and not as a copy. This will help to modify the original document if required through the results itself.

Thanks.

**Comment by brettz9** [comment]
The previously mentioned changes (allowing modification of the object) have been integrated. If my previous comments don't address your concern, please feel free to comment, and I can re-open.

**Comment by brettz9** [comment]
Specifically, you can request `resultType: "all"` and utilize the `parent` and `parentProperty` to modify the object. The `callback` option may also come in handy if you wish to modify during iteration.
