### ISSUE TITLE
Slowly and wrong result with json object with huge html files

### ISSUE THREAD

**Issue by jamesjara** [s3u/JSONPath#80]
I'm not able to get the following data correctly and it is taking so much time for the task, can you giveme some direction , thanks
(token valid 1 day)
https://api.shodan.io/shodan/host/search?key=MM72AkzHXdHpC8iP65VVEEVrJjp7zkgd&minify=true&query=apache
**responsePath key is using JSONPath**
`
      "connector": "rest",
      "debug": "true",
      "operations": [{
        "template": {
          "method": "GET",
          "url": "https://api.shodan.io/shodan/host/search?key=MM72AkzHXdHpC8iP65VVEEVrJjp7zkgd&minify=true&query=apache",
          "headers": {
            "accepts": "application/json",
            "content-type": "application/json"
          },
          "query": {
            "queryw": "{query}"
          },
          "responsePath": "$.."
        }, 
      }]
`

**Comment by brettz9** [comment]
That data is not a complete JSON file at the moment.

Also, if you still have the problem, can you put up an example on JSFiddle with the sample data baked in (and modified if necessary) so we can more easily test?

**Comment by jamesjara** [comment]
Thanks, @brettz9  to me the JSON is loading 100%, what it is missing there, the endpoint is responding with big HTML encoded properties, could be related to the issue, any way, I end using the raw response,  so we can close this, thanks
