### ISSUE TITLE
Update for changes in remark, remark-lint

### ISSUE THREAD

**Issue by wooorm** [s3u/JSONPath#82]
[`remark`](https://github.com/wooorm/remark) and [`remark-lint`](https://github.com/wooorm/remark-lint) changed a bunch since it was implemented here. Most notably, see the [`remark-lint@6.0.0`](https://github.com/wooorm/remark-lint/releases/tag/6.0.0) changelog, and the [releases for `remark`](https://github.com/wooorm/remark/releases) page to find out more.

Or, feel free to ping us on [Gitter](https://gitter.im/wooorm/remark) or me below!

Cheers 👋
Titus

**Comment by brettz9** [comment]
Thanks! Sounds good... Taking things easy these days, but hope to get to it a bit later on.

**Comment by brettz9** [comment]
I've finally gotten around to this...Fixed in `master`, thanks!

Btw, I might offer the idea of going with the `@remark/` or `@remark-lint/` approach, to avoid having so many separate folders...
