### ISSUE TITLE
can we use jsonpath for setting a value

### ISSUE THREAD

**Issue by xycloud** [s3u/JSONPath#84]
AFAIK, we always use jsonpath for getting value from a json object, is that possible to set a value by jsonpath?

**Comment by brettz9** [comment]
Yes, the objects returned are not copies... However, as with all JavaScript objects, if you are modifying a scalar value within an object (i.e., not an array or object), you will need the parent object and the property name to modify.

You can use `resultType: 'all'` with JSONPath Plus, to get the `parent` and `parentProperty` to reference the parent object and property you wish to modify.

Closing as that should answer the question, but feel free to comment further as needed.

**Comment by xblurx** [comment]
hi there, just found that question and wanted to ask what is the actual api for setting the object value at path with `JSONPath` ?

**Comment by xblurx** [comment]
no need to answer as I found the answer in https://github.com/JSONPath-Plus/JSONPath/issues/126
