### ISSUE TITLE
Filter is not working in JsonPath

### ISSUE THREAD

**Issue by sathish-ajira** [s3u/JSONPath#85]
![screen shot 2018-08-06 at 1 02 19 pm](https://user-images.githubusercontent.com/25893181/43703009-281933ac-9979-11e8-8f1d-cc6906a4226c.png)

**Comment by brettz9** [comment]
If you were using object shorthand to add the filter, this has now been fixed... Otherwise, please add a new issue with some clear details on how to replicate...
