### ISSUE TITLE
jsonPath is not a function.

### ISSUE THREAD

**Issue by jkindwall** [s3u/JSONPath#94]
Did npm install jsonpath-plus.

At the top of my script, I have:

    const {jsonPath} = require('jsonpath-plus');

Later in my script, I have:

    let jpResult = jsonPath({ path: '[?(@.createdBy=="Bob")].name', json: result.json });

When I run this, I get:

(node:18620) UnhandledPromiseRejectionWarning: TypeError: jsonPath is not a function.

Am I missing something?

**Comment by brettz9** [comment]
The case is significant. It should be:

```js
const {JSONPath} = require('jsonpath-plus');
```

Feel free to comment further, but closing as that should address the question.
