### ISSUE TITLE
peer dependency on core-js-bundle

### ISSUE THREAD

**Issue by esetnik** [s3u/JSONPath#95]
It appears that this package is using `core-js-bundle` only as a dev dependency yet it is listed in the project as a peer dependency. This causes warnings during installation of `serverless-offline` which has a dependency on `jsonpath-plus`. See https://github.com/dherault/serverless-offline/issues/707#issuecomment-500831110

**Comment by brettz9** [comment]
I've replied over in https://github.com/dherault/serverless-offline/issues/707#issuecomment-500845763 . A project can ignore the warnings, but it is possible some environments may need core-js, as the Babel builds still may assume the presence of some globals, etc.

**Comment by brettz9** [comment]
Closing therefore, but feel free to comment further if you wish.

**Comment by brettz9** [comment]
I went ahead and reverted it in https://github.com/s3u/JSONPath/releases/tag/v0.20.1 . See the discussion at https://github.com/dherault/serverless-offline/issues/707 if interested in the rationales.
